In [2]:
! pip install numpy

  Using cached numpy-2.0.2-cp39-cp39-macosx_14_0_arm64.whl.metadata (60 kB)
Using cached numpy-2.0.2-cp39-cp39-macosx_14_0_arm64.whl (5.3 MB)


In [3]:
# import 
import numpy as np

# Beginner Level (1–30)

Create a NumPy array containing numbers from 1 to 10.

In [5]:
array_1_to_10 = np.arange(1,11)
print(array_1_to_10)

[ 1  2  3  4  5  6  7  8  9 10]


Create a NumPy array of all zeros with length 10.

In [6]:
all_zeros = np.zeros(10)
print(all_zeros)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


Create a NumPy array of all ones with shape (3, 4).

In [7]:
all_ones = np.ones((3,4))
print(all_ones)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


Create an array of even numbers from 2 to 20.

In [8]:
even_number = np.arange(2,21,2)
print(even_number)

[ 2  4  6  8 10 12 14 16 18 20]


Create an array of 10 equally spaced values between 0 and 1.

In [11]:
linner_space_array = np.linspace(0,1,10)
print(linner_space_array)

[0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]


Create a 3×3 identity matrix.

In [13]:
matrix_3_x_3 = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(matrix_3_x_3)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


Check the shape, size, and dimensions of an array.

In [18]:
print(f"""
Shape : {matrix_3_x_3.shape}
Size : {matrix_3_x_3.size}
Dimension : {matrix_3_x_3.ndim} 
""")


Shape : (3, 3)
Size : 9
Dimension : 2 



Convert a Python list into a NumPy array.

In [19]:
numpy_list = np.array([1,2,3,4,5])
print(numpy_list)

[1 2 3 4 5]


Change the datatype of an array from integer to float.

In [20]:
numpy_list.astype('float')

array([1., 2., 3., 4., 5.])

Create a random array of size 5.

In [25]:
random_array = np.random.rand(5)
print(random_array)

[0.89968361 0.59517397 0.18434158 0.24545851 0.85392157]


Access the third element of an array.

In [27]:
print(random_array[2])

0.1843415810140976


Access the last element of an array.

In [28]:
print(random_array[-1])

0.8539215694882718


Slice the first five elements of an array.

In [29]:
print(random_array[:5])

[0.89968361 0.59517397 0.18434158 0.24545851 0.85392157]


Reverse an array using slicing.

In [30]:
print(random_array[::-1])

[0.85392157 0.24545851 0.18434158 0.59517397 0.89968361]


Extract all even-indexed elements from an array.

In [34]:
print(random_array[::2])

[0.89968361 0.18434158 0.85392157]


Replace the first element of an array with 100.

In [36]:
random_array[0]=100
print(random_array)

[100.           0.59517397   0.18434158   0.24545851   0.85392157]


Create a 4×4 matrix and access its second row.

In [38]:
matrix_4x4 = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]])
print(matrix_4x4[2])

[ 9 10 11 12]


Extract the third column from a matrix.

In [46]:
print(matrix_4x4[:,2])

[ 3  7 11 15]


Find the shape of a 5×5 matrix.

In [49]:
one_5x5 = np.ones((5,5))
print(one_5x5)
print(one_5x5.shape)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
(5, 5)


Reshape an array of 12 elements into a 3×4 matrix.

In [53]:
array = np.arange(0,12)

print(array)
reshape = array.reshape((3,4))
print(reshape)

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


Perform element-wise addition of two arrays.

In [56]:
ones_array = np.ones(5)
print(random_array,'\n****\n',ones_array,"\n****")
print(random_array+ones_array)

[100.           0.59517397   0.18434158   0.24545851   0.85392157] 
****
 [1. 1. 1. 1. 1.] 
****
[101.           1.59517397   1.18434158   1.24545851   1.85392157]


Perform element-wise subtraction.

In [57]:
ones_array = np.ones(5)
print(random_array,'\n****\n',ones_array,"\n****")
print(random_array - ones_array)

[100.           0.59517397   0.18434158   0.24545851   0.85392157] 
****
 [1. 1. 1. 1. 1.] 
****
[99.         -0.40482603 -0.81565842 -0.75454149 -0.14607843]


Multiply two arrays element-wise.

In [58]:
ones_array = np.ones(5)
print(random_array,'\n****\n',ones_array,"\n****")
print(random_array * ones_array)

[100.           0.59517397   0.18434158   0.24545851   0.85392157] 
****
 [1. 1. 1. 1. 1.] 
****
[100.           0.59517397   0.18434158   0.24545851   0.85392157]


Divide two arrays element-wise.

In [59]:
ones_array = np.ones(5)
print(random_array,'\n****\n',ones_array,"\n****")
print(random_array / ones_array)

[100.           0.59517397   0.18434158   0.24545851   0.85392157] 
****
 [1. 1. 1. 1. 1.] 
****
[100.           0.59517397   0.18434158   0.24545851   0.85392157]


Square every element in an array.

In [62]:
print(random_array,'\n****\n')
print(random_array * random_array)
print(random_array ** 2)

[100.           0.59517397   0.18434158   0.24545851   0.85392157] 
****

[1.00000000e+04 3.54232059e-01 3.39818185e-02 6.02498800e-02
 7.29182047e-01]
[1.00000000e+04 3.54232059e-01 3.39818185e-02 6.02498800e-02
 7.29182047e-01]


Find the sum of all elements in an array.

In [65]:
print(random_array.sum())

101.87889563422708


Find the mean of an array.

In [66]:
print(random_array.mean())

20.375779126845416


Find the maximum and minimum values.

In [67]:
print('min : ',random_array.min())
print('max : ',random_array.max())

min :  0.1843415810140976
max :  100.0


Find the index of the largest value.

In [75]:

arr = np.array([10, 20, 30, 40, 30, 50])

indices = np.where(arr == arr.max())[0]
print(indices)  



[5]



Calculate the standard deviation of an array.


In [76]:
print(arr.std())

12.909944487358056
