In [99]:
import numpy as np

# Easy-Intermediate Level (31–60)


Create a 5×5 matrix filled with random integers.

In [100]:
matrix_5x5 = np.random.rand(5,5)*100
print(matrix_5x5)

[[40.73352129 74.54041533 30.71938638 82.03574885 28.1819524 ]
 [94.89670301  9.26310166 66.06271083 51.99310763 71.39906832]
 [10.49714848 89.11255612 19.25509002 36.45800068  6.34982411]
 [73.28754767 62.15153531 48.89814112  3.18565882 75.93671379]
 [73.32112657 34.64256007 70.43269574 89.88942358 99.46319042]]


Find all values greater than 50 in an array.

In [101]:
print(matrix_5x5[matrix_5x5>50])

[74.54041533 82.03574885 94.89670301 66.06271083 51.99310763 71.39906832
 89.11255612 73.28754767 62.15153531 75.93671379 73.32112657 70.43269574
 89.88942358 99.46319042]


Replace all negative values with zero.

In [102]:
matrix_5x5[matrix_5x5 < 10] = 0
print(matrix_5x5)



[[40.73352129 74.54041533 30.71938638 82.03574885 28.1819524 ]
 [94.89670301  0.         66.06271083 51.99310763 71.39906832]
 [10.49714848 89.11255612 19.25509002 36.45800068  0.        ]
 [73.28754767 62.15153531 48.89814112  0.         75.93671379]
 [73.32112657 34.64256007 70.43269574 89.88942358 99.46319042]]


Count how many values are greater than 25.

In [103]:
matrix_5x5[matrix_5x5 >25].size

20

Find unique elements in an array.

In [104]:
np.unique(matrix_5x5)

array([ 0.        , 10.49714848, 19.25509002, 28.1819524 , 30.71938638,
       34.64256007, 36.45800068, 40.73352129, 48.89814112, 51.99310763,
       62.15153531, 66.06271083, 70.43269574, 71.39906832, 73.28754767,
       73.32112657, 74.54041533, 75.93671379, 82.03574885, 89.11255612,
       89.88942358, 94.89670301, 99.46319042])

In [106]:
# Sort an array in ascending order.

In [107]:
np.sort(matrix_5x5)

array([[28.1819524 , 30.71938638, 40.73352129, 74.54041533, 82.03574885],
       [ 0.        , 51.99310763, 66.06271083, 71.39906832, 94.89670301],
       [ 0.        , 10.49714848, 19.25509002, 36.45800068, 89.11255612],
       [ 0.        , 48.89814112, 62.15153531, 73.28754767, 75.93671379],
       [34.64256007, 70.43269574, 73.32112657, 89.88942358, 99.46319042]])

Sort an array in descending order.

In [108]:
res = np.sort(matrix_5x5)
res[::-1]

array([[34.64256007, 70.43269574, 73.32112657, 89.88942358, 99.46319042],
       [ 0.        , 48.89814112, 62.15153531, 73.28754767, 75.93671379],
       [ 0.        , 10.49714848, 19.25509002, 36.45800068, 89.11255612],
       [ 0.        , 51.99310763, 66.06271083, 71.39906832, 94.89670301],
       [28.1819524 , 30.71938638, 40.73352129, 74.54041533, 82.03574885]])

Find the frequency of each unique value.


In [109]:
np.unique_counts(matrix_5x5)

UniqueCountsResult(values=array([ 0.        , 10.49714848, 19.25509002, 28.1819524 , 30.71938638,
       34.64256007, 36.45800068, 40.73352129, 48.89814112, 51.99310763,
       62.15153531, 66.06271083, 70.43269574, 71.39906832, 73.28754767,
       73.32112657, 74.54041533, 75.93671379, 82.03574885, 89.11255612,
       89.88942358, 94.89670301, 99.46319042]), counts=array([3, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1]))

Remove duplicate values from an array.

In [110]:
np.unique(matrix_5x5)

array([ 0.        , 10.49714848, 19.25509002, 28.1819524 , 30.71938638,
       34.64256007, 36.45800068, 40.73352129, 48.89814112, 51.99310763,
       62.15153531, 66.06271083, 70.43269574, 71.39906832, 73.28754767,
       73.32112657, 74.54041533, 75.93671379, 82.03574885, 89.11255612,
       89.88942358, 94.89670301, 99.46319042])

Merge two arrays into one.


In [111]:
a = np.array([1,2,3,4])
b = np.array([4,5,6,7])
np.concatenate([a,b])


array([1, 2, 3, 4, 4, 5, 6, 7])

Stack two arrays vertically.


In [112]:
np.stack([a,b])

array([[1, 2, 3, 4],
       [4, 5, 6, 7]])

Stack two arrays horizontally.

In [113]:
np.stack([a,b],axis=1)

array([[1, 4],
       [2, 5],
       [3, 6],
       [4, 7]])

Split an array into 4 equal parts.

In [114]:
np.split(a,4)

[array([1]), array([2]), array([3]), array([4])]


Flatten a 2D array.

In [115]:
np.ravel(matrix_5x5)

array([40.73352129, 74.54041533, 30.71938638, 82.03574885, 28.1819524 ,
       94.89670301,  0.        , 66.06271083, 51.99310763, 71.39906832,
       10.49714848, 89.11255612, 19.25509002, 36.45800068,  0.        ,
       73.28754767, 62.15153531, 48.89814112,  0.        , 75.93671379,
       73.32112657, 34.64256007, 70.43269574, 89.88942358, 99.46319042])

Convert a 3×4 matrix into a 1D array.

In [116]:
d2 = np.array(
    [[1,2,3,4],
    [5,6,7,8],
    [9,10,11,12]]
)

d2.ravel()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

Create a checkerboard pattern matrix.

In [117]:
checkboard = np.zeros((4,4))
checkboard[::2,1::2]=1
checkboard[1::2,::2]=1
checkboard

array([[0., 1., 0., 1.],
       [1., 0., 1., 0.],
       [0., 1., 0., 1.],
       [1., 0., 1., 0.]])

Create a diagonal matrix from an array.

In [118]:
checkboard = np.zeros((4,4))
for i in range(0,4):
    checkboard[i,i]=1

checkboard

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

Extract the diagonal elements of a matrix.

In [119]:
for i in range(0,4):
    print(checkboard[i,i])

1.0
1.0
1.0
1.0


Find row-wise sums of a matrix.


In [120]:
np.add(a,b)

array([ 5,  7,  9, 11])

Find column-wise sums of a matrix.

In [121]:
np.sum([a,b],axis=1)

array([10, 22])

Find row-wise maximum values.


In [122]:
np.max(d2,axis = 0)

array([ 9, 10, 11, 12])

Find column-wise minimum values.

In [123]:
np.max(d2,axis = 1)

array([ 4,  8, 12])


Generate 100 random integers between 1 and 100.


In [124]:
np.random.randint((1,100))[1]

np.int64(63)

Set a random seed and generate reproducible numbers.


In [127]:
np.random.random_integers(42)

/var/folders/n_/7z9tgm7508z7_wn1z6d0p3fw0000gn/T/ipykernel_13335/2829190210.py:1: DeprecationWarning: This function is deprecated. Please call randint(1, 42 + 1) instead
  np.random.random_integers(42)


np.int64(27)

Find all indices where values are greater than 30.

In [134]:
x = np.arange(0,50,5)
print(x)
np.where(x > 30)[0]

[ 0  5 10 15 20 25 30 35 40 45]


array([7, 8, 9])

Use np.where() to replace values greater than 30 with 999.


In [136]:
for i in np.where(x > 30)[0]:
    x[i]=999
print(x)

[  0   5  10  15  20  25  30 999 999 999]



Create a boolean mask for values less than 20.


In [138]:
x<20

array([ True,  True,  True,  True,  True,  True, False, False, False,
       False])

Filter all odd numbers from an array.


In [139]:
x %2 !=0

array([False, False, False, False, False, False, False,  True,  True,
        True])

Count the number of even values.

In [141]:
sum(x%2==0)

np.int64(7)


Compute cumulative sum of an array.

In [147]:
arr = np.arange(1,10)
print(arr)
np.cumsum(arr)

[1 2 3 4 5 6 7 8 9]


array([ 1,  3,  6, 10, 15, 21, 28, 36, 45])