In [9]:
import numpy as np

# Easy-Intermediate Level (31–60)


Create a 5×5 matrix filled with random integers.

In [10]:
matrix_5x5 = np.random.rand(5,5)*100
print(matrix_5x5)

[[42.30922268 37.96610108 93.26264164 94.66566198 32.25869046]
 [70.04316309 67.7795624  35.25699302 27.56420831  5.62399583]
 [36.89758294 21.93831894 56.32977376 14.52711167  9.56895537]
 [24.46090237 97.77750479 72.68878728 26.28488866 27.00337831]
 [46.15564801 29.96348284 25.89051795 35.02936765 85.46921971]]


Find all values greater than 50 in an array.

In [11]:
print(matrix_5x5[matrix_5x5>50])

[93.26264164 94.66566198 70.04316309 67.7795624  56.32977376 97.77750479
 72.68878728 85.46921971]


Replace all negative values with zero.

In [12]:
matrix_5x5[matrix_5x5 < 10] = 0
print(matrix_5x5)



[[42.30922268 37.96610108 93.26264164 94.66566198 32.25869046]
 [70.04316309 67.7795624  35.25699302 27.56420831  0.        ]
 [36.89758294 21.93831894 56.32977376 14.52711167  0.        ]
 [24.46090237 97.77750479 72.68878728 26.28488866 27.00337831]
 [46.15564801 29.96348284 25.89051795 35.02936765 85.46921971]]


Count how many values are greater than 25.

In [13]:
matrix_5x5[matrix_5x5 >25].size

20

Find unique elements in an array.

In [14]:
np.unique(matrix_5x5)

array([ 0.        , 14.52711167, 21.93831894, 24.46090237, 25.89051795,
       26.28488866, 27.00337831, 27.56420831, 29.96348284, 32.25869046,
       35.02936765, 35.25699302, 36.89758294, 37.96610108, 42.30922268,
       46.15564801, 56.32977376, 67.7795624 , 70.04316309, 72.68878728,
       85.46921971, 93.26264164, 94.66566198, 97.77750479])

In [15]:
Sort an array in ascending order.

SyntaxError: invalid syntax (2205828038.py, line 1)

In [ ]:
np.sort(matrix_5x5)

array([[ 0.        , 11.289979  , 15.5644362 , 20.19461196, 93.47145537],
       [38.3089354 , 43.09141204, 43.60731648, 77.42648013, 85.92562652],
       [ 0.        , 16.95949285, 65.71411899, 95.88826436, 97.32158095],
       [ 0.        , 13.94371123, 22.92208206, 29.48087666, 90.27678103],
       [22.69409459, 23.84392294, 40.48590993, 85.40994635, 94.42441541]])

Sort an array in descending order.

In [17]:
res = np.sort(matrix_5x5)
res[::-1]

array([[25.89051795, 29.96348284, 35.02936765, 46.15564801, 85.46921971],
       [24.46090237, 26.28488866, 27.00337831, 72.68878728, 97.77750479],
       [ 0.        , 14.52711167, 21.93831894, 36.89758294, 56.32977376],
       [ 0.        , 27.56420831, 35.25699302, 67.7795624 , 70.04316309],
       [32.25869046, 37.96610108, 42.30922268, 93.26264164, 94.66566198]])

Find the frequency of each unique value.


In [16]:
np.unique_counts(matrix_5x5)

UniqueCountsResult(values=array([ 0.        , 14.52711167, 21.93831894, 24.46090237, 25.89051795,
       26.28488866, 27.00337831, 27.56420831, 29.96348284, 32.25869046,
       35.02936765, 35.25699302, 36.89758294, 37.96610108, 42.30922268,
       46.15564801, 56.32977376, 67.7795624 , 70.04316309, 72.68878728,
       85.46921971, 93.26264164, 94.66566198, 97.77750479]), counts=array([2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1]))

Remove duplicate values from an array.

In [21]:
np.unique(matrix_5x5)

array([ 0.        , 14.52711167, 21.93831894, 24.46090237, 25.89051795,
       26.28488866, 27.00337831, 27.56420831, 29.96348284, 32.25869046,
       35.02936765, 35.25699302, 36.89758294, 37.96610108, 42.30922268,
       46.15564801, 56.32977376, 67.7795624 , 70.04316309, 72.68878728,
       85.46921971, 93.26264164, 94.66566198, 97.77750479])

Merge two arrays into one.


In [30]:
a = np.array([1,2,3,4])
b = np.array([4,5,6,7])
np.concatenate([a,b])


array([1, 2, 3, 4, 4, 5, 6, 7])

Stack two arrays vertically.


In [31]:
np.stack([a,b])

array([[1, 2, 3, 4],
       [4, 5, 6, 7]])

Stack two arrays horizontally.

In [32]:
np.stack([a,b],axis=1)

array([[1, 4],
       [2, 5],
       [3, 6],
       [4, 7]])

Split an array into 4 equal parts.

In [33]:
np.split(a,4)

[array([1]), array([2]), array([3]), array([4])]


Flatten a 2D array.

In [20]:
np.ravel(matrix_5x5)

array([42.30922268, 37.96610108, 93.26264164, 94.66566198, 32.25869046,
       70.04316309, 67.7795624 , 35.25699302, 27.56420831,  0.        ,
       36.89758294, 21.93831894, 56.32977376, 14.52711167,  0.        ,
       24.46090237, 97.77750479, 72.68878728, 26.28488866, 27.00337831,
       46.15564801, 29.96348284, 25.89051795, 35.02936765, 85.46921971])

Convert a 3×4 matrix into a 1D array.

In [37]:
d2 = np.array(
    [[1,2,3,4],
    [5,6,7,8],
    [9,10,11,12]]
)

d2.ravel()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

Create a checkerboard pattern matrix.

In [71]:
checkboard = np.zeros((4,4))
checkboard[::2,1::2]=1
checkboard[1::2,::2]=1
checkboard

array([[0., 1., 0., 1.],
       [1., 0., 1., 0.],
       [0., 1., 0., 1.],
       [1., 0., 1., 0.]])

Create a diagonal matrix from an array.

In [72]:
checkboard = np.zeros((4,4))
for i in range(0,4):
    checkboard[i,i]=1

checkboard

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

Extract the diagonal elements of a matrix.

In [73]:
for i in range(0,4):
    print(checkboard[i,i])

1.0
1.0
1.0
1.0


Find row-wise sums of a matrix.


In [75]:
np.add(a,b)

array([ 5,  7,  9, 11])

Find column-wise sums of a matrix.

In [80]:
np.sum([a,b],axis=1)

array([10, 22])

Find row-wise maximum values.


In [83]:
np.max(d2,axis = 0)

array([ 9, 10, 11, 12])

Find column-wise minimum values.

In [82]:
np.max(d2,axis = 1)

array([ 4,  8, 12])


Generate 100 random integers between 1 and 100.


In [98]:
np.random.randint((1,100))[1]

np.int64(72)

Set a random seed and generate reproducible numbers.


Find all indices where values are greater than 30.

Use np.where() to replace values greater than 50 with 999.



Create a boolean mask for values less than 20.


Filter all odd numbers from an array.


Count the number of even values.


Compute cumulative sum of an array.